version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - repacker examples/delta-builds/base-centos.yml -d
      - repacker examples/delta-builds/postgres.yml -d

